### PR TITLE
Functional Control panel

### PR DESCRIPTION
**Pull request by adeebshihadeh**
It functions, but not sure that you want to merge it. I am not sure I followed the coding conventions smoothie uses. Also, sorry for the big pull request.

### CODE REVIEW

**Comment by adeebshihadeh** [comment]
It should also search for "config" as well as "config.txt" when retrieving the machine's configuration.

**Comment by adeebshihadeh** [comment]
I'll make the printer control panel a separate module from the main control panel.

**Comment by arthurwolf** [comment]
Hey !

So first off, thanks a lot for this :)

So, the reason why I'm not releasing Mousse yet, is because I want it to be built in a very particular fashion, and I haven't yet had time to either code, or describe what that structure is.

Some notes about what you did so far, that should help you a bit with understanding the direction I want things to take : 

1 : Here https://github.com/arthurwolf/Mousse/pull/1/files#diff-01ebe5fc1f6a2053b4e01bc743c5e98eR106 you use an event to send a g-code. We don't want to use events for -everything-, events are used when there is potentially several modules listenting for it. In the case of sent G-codes, there is only one other module that would be interrested, so we don't use an event call, but call that module directly ( because it is a "core" module that can not be removed, it will always be there ).
Instead, we can simply call this machine's "interface" module : https://github.com/arthurwolf/Mousse/blob/master/modules/machines/interface.js#L21
Here is an example of how to use this : https://github.com/arthurwolf/Mousse/blob/master/modules/machines/updater/updater.js#L23
Amongst other things, the "interface" module makes sure it doesn't send more than one request at a time to the Smoothieboard, because that could crash it.

2 : Here https://github.com/arthurwolf/Mousse/pull/1/files#diff-01ebe5fc1f6a2053b4e01bc743c5e98eR264
you call the smoothieboard to ask for temperature. 
But it is not the responsability of the the control interface to ask the smotohieboard for things, it's the responsabilety of the "machine" module, more specifically it's "updater" module : https://github.com/arthurwolf/Mousse/blob/master/modules/machines/updater/updater.js
That module then calls the "on_value_update" event. That's the event you want to register for to get your information.

I think a good first step would be changing those two things.

But then there is even more crazyness : 

3 : Essentially right now, you have -one- module : the "controlscreen" module.
But you want many more than that ! You want a "fan control" module, a "temperature control" module, a "temperature graph" module : one module per widget thingie !
The only role of controlscreen, is to call those modules to ask them to display things on it's page.

So say a machine has a fan control. Here's what happens : 
- The "controlscreen" module calls the "on_populate_control_screen" event, with the machine this screen is about, as a parameter.
- The "controlscreenfancontrolwidget" module receives that event, checks if this machine actually has fan controls ( from config ), and if so, creates a new "fancontrolwidget" object, 
- Then this "fancontrolwidget" module calls the "controlscreen" module and asks it to display the fan interface it just created.

Does that make any kind of sense ?

Tell me :)

Cheers !

**Comment by adeebshihadeh** [comment]
I think I understand now. So should each widget have its own HTML file?

**Comment by arthurwolf** [comment]
Yes, each module should have it's own HTML file ( you can look at existing modules, there are mechanisms in place to allow modules to have their own html files and retreive them ( called assets, see for example : https://github.com/arthurwolf/Mousse/blob/master/modules/gui/screens/machineconfigurationscreen/module.js#L25 )

Cheers !

**Comment by adeebshihadeh** [comment]
In terms of the filescreen, how should commands such as "play /sd/file.gcode" be sent? Should it be a separate module in machines?

**Pull request closed without merging**
